check requirement number field
novius-os/noviusos_form pull request #51
Opened 2017-06-14 15:25 UTC by cholletNovius

There was no requirerment for number field. As default, it was the abstract method it was used :
`return is_string($inputValue) && $inputValue !== '';`

2017-06-14 16:05 UTC, jguyomard approved these changes

2017-06-15 07:18 UTC, mesa-novius commented
Being picky I know....

if $inputValue can be empty, it could be more "logical" like this:

```
!empty($inputValue) && is_int($inputValue);
```

We do not want to evaluate empty variables!

2017-06-15 07:33 UTC, tonyyb requested changes

2017-06-15 07:33 UTC, tonyyb commented on classes/driver/field/input/number.php
> +        return is_int($inputValue) && !empty($inputValue);
Will return false if "0" is sent because of `!empty($inputValue)`.

Also $inputValue is already casted in (int) before.

2017-06-15 08:38 UTC, shaoshiva approved these changes
:+1:

2017-06-15 08:47 UTC, merged